windowrule = float, class:^(pavucontrol)$
windowrule = float, class:^(nm-connection-editor)$
windowrule = float, class:^(org.pulseaudio.pavucontrol)$
windowrule = float, class:^(blueman-manager)$
windowrule = size 1000 700, class:^(thunar)$, title:^(File Operation Progress)$
windowrule = workspace 2, class:^(firefox)$
windowrule = workspace 3, class:^(thunar)$
windowrule = workspace 4, class:^(Spotify)$
