windowrule {
  name = pavucontrol-floating
  match:class = ^(pavucontrol)$
  float = on
}

windowrule {
  name = network-editor-floating
  match:class = ^(nm-connection-editor)$
  float = on
}

windowrule {
  name = pulseaudio-pavucontrol-floating
  match:class = ^(org.pulseaudio.pavucontrol)$
  float = on
}

windowrule {
  name = blueman-manager-floating
  match:class = ^(blueman-manager)$
  float = on
}

windowrule {
  name = thunar-file-operation-size
  match:class = ^(thunar)$
  match:title = ^(File Operation Progress)$
  size = 1000 700
}

windowrule {
  name = firefox-workspace
  match:class = ^(firefox)$
  workspace = 2
}

windowrule {
  name = thunar-workspace
  match:class = ^(thunar)$
  workspace = 3
}

windowrule {
  name = spotify-workspace
  match:class = ^(Spotify)$
  workspace = 4
}
