windowrule {
  match:class = ^(pavucontrol)$
  float = on
}

windowrule {
  match:class = ^(nm-connection-editor)$
  float = on
}

windowrule {
  match:class = ^(org.pulseaudio.pavucontrol)$
  float = on
}

windowrule {
  match:class = ^(blueman-manager)$
  float = on
}

windowrule {
  match:class = ^(thunar)$
  match:title = ^(File Operation Progress)$
  size = 1000 700
}

windowrule {
  match:class = ^(firefox)$
  workspace = 2
}

windowrule {
  match:class = ^(thunar)$
  workspace = 3
}

windowrule {
  match:class = ^(Spotify)$
  workspace = 4
}
