set -g prefix C-Space
unbind C-b
bind C-Space send-prefix

set -g mouse on
set -g history-limit 100000
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g default-terminal "tmux-256color"
set -g status-position top

bind v split-window -h
bind h split-window -v
bind x kill-pane
bind z resize-pane -Z

bind -r H select-pane -L
bind -r J select-pane -D
bind -r K select-pane -U
bind -r L select-pane -R

bind -r Left resize-pane -L 5
bind -r Right resize-pane -R 5
bind -r Up resize-pane -U 5
bind -r Down resize-pane -D 5

run '~/.tmux/plugins/tpm/tpm'
